# Generated by Django 5.1.4 on 2024-12-19 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ongaku", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["display_name"], name="ongaku_user_display_b0510d_idx"
            ),
        ),
    ]
